-- Phase 4 Tier 2.5 phase C-1 follow-on
-- (system-documentation/plans/oms-aeron-cluster-substrate.md): same shape of fix as V30,
-- but for ledger_inflight_outbox.
--
-- Why we need it: post-V30 verification on Pop! 2026-05-14 showed the bottleneck shifted
-- from `domain_event_outbox` to `ledger_inflight_outbox`. The reconciler SELECT
--   SELECT id, order_id, payload_json::text, created_at, attempts
--   FROM ledger_inflight_outbox
--   WHERE published_at IS NULL AND compensated_at IS NULL AND created_at <= $1
--   ORDER BY id LIMIT $2 FOR UPDATE SKIP LOCKED
-- still picks `ledger_inflight_outbox_pkey` (because `ORDER BY id` matches pkey
-- ordering), then filters out 42 972 rows under LockRows to surface 200 — 15 ms per call,
-- 10.95 ms mean across the burst (15.2 % of all Postgres time post-V30, top of
-- pg_stat_statements).
--
-- The existing partial index `idx_ledger_inflight_outbox_pending btree (created_at) WHERE
-- published_at IS NULL` (V4) is on the wrong column to satisfy ORDER BY id, and missing
-- the `compensated_at IS NULL` predicate. The existing
-- `idx_ledger_inflight_outbox_failed_uncompensated btree (attempts, last_attempt_at)
-- WHERE published_at IS NULL AND compensated_at IS NULL` (V29) is on the right predicate
-- but ordered by (attempts, last_attempt_at), so the planner cannot use it for ORDER BY
-- id either.
--
-- This new index gives the planner a single index that satisfies all of:
--   (1) WHERE published_at IS NULL  AND compensated_at IS NULL  -- partial predicate
--   (2) ORDER BY id                                             -- index column
-- so the scan walks only matching rows in id order. The other two indexes stay in place;
-- they serve different predicates (the V29 compensator scan uses (attempts,
-- last_attempt_at) ordering, V4 is unused after V30+V31 but kept for safety).
-- flyway:executeInTransaction=false

-- Note: COMMENT ON INDEX kept in the migration file's own header above (same reason as V30
-- — Flyway 10 + executeInTransaction=false rejects mixing non-transactional CREATE INDEX
-- CONCURRENTLY with transactional COMMENT in the same migration).
--
-- 2026-05-18: dropped CONCURRENTLY but kept the executeInTransaction=false pragma so the
-- on-disk content matches what Pop's slice-4p bench applied (the user's local Pop-only edit
-- ahead of this commit). Background: Pop runs OMS through the Supabase pgbouncer in
-- transaction-pool mode, where pgbouncer wraps every statement in a transaction and
-- rejects CONCURRENTLY with "cannot run inside a transaction block". Plain CREATE INDEX IF
-- NOT EXISTS produces the SAME index — it just holds an AccessExclusiveLock on
-- ledger_inflight_outbox briefly while building. For Wed-demo / single-host bench this is
-- fine; for production cutover use a direct (non-pgbouncer) connection so CONCURRENTLY can
-- come back.
CREATE INDEX IF NOT EXISTS idx_ledger_inflight_outbox_pending_id
    ON ledger_inflight_outbox (id)
    WHERE published_at IS NULL AND compensated_at IS NULL;
